#!/bin/zsh

dotnet add package Microsoft.Extensions.ApiDescription.Server --version '10.0.0-preview.1.*'

f=$(ls *.csproj)

tmpfile=${f/.csproj/.tmp}
{
    awk '/<ItemGroup>/ { f = 1 } !f' $f
    cat <<EOF
  <PropertyGroup>
    <OpenApiDocumentsDirectory>\$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
  </PropertyGroup>

EOF
    awk '/<ItemGroup>/ { f = 1 } f' $f
} > $tmpfile

mv $tmpfile $f
